"""Stem acquisition: either run demucs-infer / htdemucs, or reuse pinned stems.

This module knows about Demucs and nothing else. When it separates, it writes four stems
into one flat directory; the nested per-track hierarchy Demucs' own CLI produces is not
part of our output contract.

It can also take stems that already exist. That matters because htdemucs is not
bit-reproducible on the same GPU with the same input, so separation is the point where
run-to-run variation enters the pipeline. Supplying the same stems twice removes that
variable; regenerating them does not. Supplied stems are treated as strictly read-only.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import NamedTuple

import soundfile as sf
import torch

PACKAGE = "demucs-infer"
VERSION = "4.2.2"
MODEL = "htdemucs"
METHOD = "{0} {1} / {2}".format(PACKAGE, VERSION, MODEL)

#: What a supplied stem directory must contain, and what separation writes.
STEM_NAMES = ("drums", "bass", "other", "vocals")
STEM_FILENAME = "{0}.wav"

#: The Analyzer cannot verify that supplied stems came from the given audio, so it says
#: so rather than claiming a production method it did not observe.
SUPPLIED_METHOD = ("supplied to this run as pinned stems; not generated by the Analyzer "
                   "and the production method is unverified")

#: How far a supplied stem's duration may sit from the source audio's before it is
#: rejected as unrelated. Generous enough for resampling edge effects, tight enough that
#: a different track does not slip through on length alone.
DURATION_TOLERANCE_SEC = 0.5


class SeparationResult(NamedTuple):
    stem_paths: dict          # name -> Path
    sample_rate: int
    seconds: float
    max_cuda_allocated: int
    max_cuda_reserved: int
    mode: str                 # "generated" or "supplied"
    stems_dir: Path


class StemValidationError(ValueError):
    """A supplied stem directory cannot be used. Never falls back to regeneration."""


def separate(audio_path, stems_dir, device="cuda") -> SeparationResult:
    """Separate `audio_path` into four stems written directly into `stems_dir`."""
    from demucs_infer.api import AudioFile
    from demucs_infer.apply import apply_model
    from demucs_infer.audio import save_audio
    from demucs_infer.pretrained import get_model

    stems_dir = Path(stems_dir)
    stems_dir.mkdir(parents=True, exist_ok=True)

    model = get_model(MODEL)
    model.eval()
    model.to(torch.device(device))

    wav = AudioFile(audio_path).read(
        streams=0, samplerate=model.samplerate, channels=model.audio_channels
    )
    reference = wav.mean(0)
    normalised = (wav - reference.mean()) / reference.std()

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    torch.cuda.synchronize()
    started = time.perf_counter()
    sources = apply_model(
        model, normalised[None], device=torch.device(device),
        shifts=1, split=True, overlap=0.25, progress=False,
    )[0]
    torch.cuda.synchronize()
    seconds = time.perf_counter() - started

    sources = sources * reference.std() + reference.mean()

    stem_paths = {}
    for name, source in zip(model.sources, sources):
        target = stems_dir / "{0}.wav".format(name)
        save_audio(source.cpu(), target, samplerate=model.samplerate)
        stem_paths[name] = target

    missing = set(STEM_NAMES) - set(stem_paths)
    if missing:
        raise RuntimeError(
            "{0} did not produce the expected stems; missing {1}".format(MODEL, sorted(missing))
        )

    result = SeparationResult(
        stem_paths=stem_paths,
        sample_rate=int(model.samplerate),
        seconds=seconds,
        max_cuda_allocated=torch.cuda.max_memory_allocated(),
        max_cuda_reserved=torch.cuda.max_memory_reserved(),
        mode="generated",
        stems_dir=stems_dir,
    )
    del sources, normalised, wav, model
    torch.cuda.empty_cache()
    return result


def load_supplied(stems_dir, source_duration_sec) -> SeparationResult:
    """Validate and adopt stems that already exist, without running separation.

    Raises StemValidationError rather than falling back to regenerating: a run asked to
    use pinned stems that silently separated instead would produce a document whose
    reproducibility claim is false.

    Nothing here writes to `stems_dir`; the files are only opened for metadata.
    """
    stems_dir = Path(stems_dir).expanduser().resolve()
    if not stems_dir.exists():
        raise StemValidationError("stems directory does not exist: {0}".format(stems_dir))
    if not stems_dir.is_dir():
        raise StemValidationError("stems path is not a directory: {0}".format(stems_dir))

    paths = {name: stems_dir / STEM_FILENAME.format(name) for name in STEM_NAMES}
    missing = sorted(name for name, path in paths.items() if not path.is_file())
    if missing:
        raise StemValidationError(
            "stems directory {0} is missing required stems: {1}\n"
            "Expected exactly: {2}".format(
                stems_dir, ", ".join(STEM_FILENAME.format(m) for m in missing),
                ", ".join(STEM_FILENAME.format(n) for n in STEM_NAMES))
        )

    infos = {}
    for name, path in paths.items():
        try:
            infos[name] = sf.info(str(path))
        except Exception as error:
            raise StemValidationError(
                "stem {0} is not readable audio: {1}".format(path, error)
            ) from error

    rates = {name: info.samplerate for name, info in infos.items()}
    if len(set(rates.values())) != 1:
        raise StemValidationError(
            "supplied stems disagree on sample rate: {0}. The branches derive their "
            "frame hops from it, so they must all match.".format(rates)
        )
    channels = {name: info.channels for name, info in infos.items()}
    if len(set(channels.values())) != 1:
        raise StemValidationError(
            "supplied stems disagree on channel count: {0}".format(channels))
    frames = {name: info.frames for name, info in infos.items()}
    if len(set(frames.values())) != 1:
        raise StemValidationError(
            "supplied stems disagree on length in frames: {0}".format(frames))

    duration = next(iter(infos.values())).duration
    drift = abs(duration - float(source_duration_sec))
    if drift > DURATION_TOLERANCE_SEC:
        raise StemValidationError(
            "supplied stems are {0:.3f} s long but the source audio is {1:.3f} s "
            "({2:.3f} s apart, tolerance {3} s). These stems do not appear to belong to "
            "this audio.".format(duration, float(source_duration_sec), drift,
                                 DURATION_TOLERANCE_SEC)
        )

    return SeparationResult(
        stem_paths=paths,
        sample_rate=int(next(iter(rates.values()))),
        seconds=0.0,
        max_cuda_allocated=0,
        max_cuda_reserved=0,
        mode="supplied",
        stems_dir=stems_dir,
    )
