"""Stem acquisition: either run demucs-infer, or reuse pinned stems.

This module knows about Demucs and nothing else. When it separates, it writes one flat
directory of stems; the nested per-track hierarchy Demucs' own CLI produces is not part
of our output contract.

It can also take stems that already exist. That matters because htdemucs is not
bit-reproducible on the same GPU with the same input, so separation is the point where
run-to-run variation enters the pipeline. Supplying the same stems twice removes that
variable; regenerating them does not. Supplied stems are treated as strictly read-only.

## Two models, and why the six-source one is the default

`htdemucs` returns four sources, with guitar and piano folded into `other`. `htdemucs_6s`
returns those two separately, which is the whole point of it here: an author charting a
guitar part needs to hear the guitar and to see where it was struck, and neither is
possible while it is mixed in with every other accompaniment instrument.

The six-source model is the same architecture with a different checkpoint, so the API,
the sample rate and the memory profile are unchanged - what differs is the length of
`model.sources`. Its guitar and piano separation is acknowledged upstream to be weaker
than its other four; that is accepted deliberately, because the goal is to *locate the
notes in time*, not to produce a release-quality guitar recording, and leakage costs
nothing for that.

`htdemucs` is kept selectable so an existing four-stem run can be reproduced.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import NamedTuple

import soundfile as sf
import torch

PACKAGE = "demucs-infer"
VERSION = "4.2.2"

#: The default model, and the only one that yields guitar and piano.
MODEL = "htdemucs_6s"

#: Every stem name each selectable model produces, in the order the Analyzer lists them.
#:
#: The order is the Analyzer's, not the model's: Demucs returns drums first, but a person
#: reading a mixer reaches for the voice and the rhythm section before the accompaniment,
#: and `stems[]` is what the Editor draws its rows from. Nothing derives meaning from the
#: position, so choosing a useful one is free.
MODEL_STEMS = {
    "htdemucs": ("vocals", "drums", "bass", "other"),
    "htdemucs_6s": ("vocals", "drums", "bass", "guitar", "piano", "other"),
}

#: The four every model produces, and therefore the only ones that may be *required*.
#:
#: A stems directory pinned before guitar and piano existed contains exactly these, and
#: must go on working - so these are what `load_supplied` insists on, and guitar and piano
#: are adopted when they happen to be there.
CORE_STEM_NAMES = ("vocals", "drums", "bass", "other")

DEFAULT_MODEL = MODEL
STEM_NAMES = MODEL_STEMS[MODEL]
STEM_FILENAME = "{0}.wav"


def stem_names(model=MODEL):
    """What `model` produces, in the Analyzer's order."""
    try:
        return MODEL_STEMS[model]
    except KeyError:
        raise ValueError(
            "unknown separation model {0!r}; this Analyzer knows {1}".format(
                model, ", ".join(sorted(MODEL_STEMS))
            )
        ) from None


def method_for(model=MODEL):
    """The prose provenance string recorded on every stem."""
    return "{0} {1} / {2}".format(PACKAGE, VERSION, model)


METHOD = method_for(MODEL)

#: The Analyzer cannot verify that supplied stems came from the given audio, so it says
#: so rather than claiming a production method it did not observe.
SUPPLIED_METHOD = ("supplied to this run as pinned stems; not generated by the Analyzer "
                   "and the production method is unverified")

#: How far a supplied stem's duration may sit from the source audio's before it is
#: rejected as unrelated. Generous enough for resampling edge effects, tight enough that
#: a different track does not slip through on length alone.
DURATION_TOLERANCE_SEC = 0.5

#: Below this a written stem is treated as a failure rather than as quiet music.
#:
#: A WAV header alone is 44 bytes, so anything at or under it holds no audio at all. The
#: check exists because a separation that half-failed used to leave a file behind that
#: every later stage would happily read as silence.
MINIMUM_STEM_BYTES = 1024


class SeparationResult(NamedTuple):
    stem_paths: dict          # name -> Path
    sample_rate: int
    seconds: float
    max_cuda_allocated: int
    max_cuda_reserved: int
    mode: str                 # "generated" or "supplied"
    stems_dir: Path
    #: Which checkpoint produced them. Empty for supplied stems, whose origin the
    #: Analyzer cannot verify. Defaulted so a caller that predates six-stem separation -
    #: including every existing test - still constructs a valid result.
    model: str = ""


class StemValidationError(ValueError):
    """A supplied stem directory cannot be used. Never falls back to regeneration."""


def separate(audio_path, stems_dir, device="cuda", model_name=MODEL) -> SeparationResult:
    """Separate `audio_path` into stems written directly into `stems_dir`."""
    from demucs_infer.api import AudioFile
    from demucs_infer.apply import apply_model
    from demucs_infer.audio import save_audio
    from demucs_infer.pretrained import get_model

    expected = stem_names(model_name)
    stems_dir = Path(stems_dir)
    stems_dir.mkdir(parents=True, exist_ok=True)

    model = get_model(model_name)
    model.eval()
    model.to(torch.device(device))

    wav = AudioFile(audio_path).read(
        streams=0, samplerate=model.samplerate, channels=model.audio_channels
    )
    reference = wav.mean(0)
    normalised = (wav - reference.mean()) / reference.std()

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    torch.cuda.synchronize()
    started = time.perf_counter()
    sources = apply_model(
        model, normalised[None], device=torch.device(device),
        shifts=1, split=True, overlap=0.25, progress=False,
    )[0]
    torch.cuda.synchronize()
    seconds = time.perf_counter() - started

    sources = sources * reference.std() + reference.mean()

    stem_paths = {}
    for name, source in zip(model.sources, sources):
        target = stems_dir / "{0}.wav".format(name)
        save_audio(source.cpu(), target, samplerate=model.samplerate)
        stem_paths[name] = target

    missing = set(expected) - set(stem_paths)
    if missing:
        raise RuntimeError(
            "{0} did not produce the expected stems; missing {1}".format(
                model_name, sorted(missing))
        )
    # Every stem is checked on the way out, not on the way in to the next stage. A file
    # that is absent or empty here means separation failed for that source, and saying so
    # now names the cause; discovered later it looks like a silent instrument.
    for name in expected:
        verify_written(stem_paths[name], name)

    result = SeparationResult(
        stem_paths={name: stem_paths[name] for name in expected},
        sample_rate=int(model.samplerate),
        seconds=seconds,
        max_cuda_allocated=torch.cuda.max_memory_allocated(),
        max_cuda_reserved=torch.cuda.max_memory_reserved(),
        mode="generated",
        stems_dir=stems_dir,
        model=model_name,
    )
    del sources, normalised, wav, model
    torch.cuda.empty_cache()
    return result


def verify_written(path: Path, name: str) -> None:
    """Fail loudly on a stem that was not really written.

    Raises RuntimeError rather than StemValidationError: this is about output the
    Analyzer just produced itself, not about input somebody handed it.
    """
    if not path.is_file():
        raise RuntimeError(
            "separation reported stem {0!r} but no file exists at {1}".format(name, path)
        )
    size = path.stat().st_size
    if size < MINIMUM_STEM_BYTES:
        raise RuntimeError(
            "stem {0!r} at {1} is {2} bytes, which cannot be audio. Separation appears to "
            "have failed for this source; the run is stopping rather than treating it as "
            "silence.".format(name, path, size)
        )


def load_supplied(stems_dir, source_duration_sec, model_name=MODEL) -> SeparationResult:
    """Validate and adopt stems that already exist, without running separation.

    Raises StemValidationError rather than falling back to regenerating: a run asked to
    use pinned stems that silently separated instead would produce a document whose
    reproducibility claim is false.

    Nothing here writes to `stems_dir`; the files are only opened for metadata.

    Only the four core stems are required. A directory pinned before guitar and piano
    existed is therefore still usable, and its guitar and piano branches simply produce
    nothing - which is the graceful degradation the contract already asks consumers to
    handle, rather than a hard failure over stems that were never generated.
    """
    stems_dir = Path(stems_dir).expanduser().resolve()
    if not stems_dir.exists():
        raise StemValidationError("stems directory does not exist: {0}".format(stems_dir))
    if not stems_dir.is_dir():
        raise StemValidationError("stems path is not a directory: {0}".format(stems_dir))

    wanted = stem_names(model_name)
    required = [name for name in wanted if name in CORE_STEM_NAMES]
    optional = [name for name in wanted if name not in CORE_STEM_NAMES]

    paths = {name: stems_dir / STEM_FILENAME.format(name) for name in required}
    missing = sorted(name for name, path in paths.items() if not path.is_file())
    if missing:
        raise StemValidationError(
            "stems directory {0} is missing required stems: {1}\n"
            "Expected at least: {2}".format(
                stems_dir, ", ".join(STEM_FILENAME.format(m) for m in missing),
                ", ".join(STEM_FILENAME.format(n) for n in required))
        )
    for name in optional:
        candidate = stems_dir / STEM_FILENAME.format(name)
        if candidate.is_file():
            paths[name] = candidate
    # Back into the Analyzer's order, so the document lists them the way it always does
    # however the dictionary happened to be filled.
    paths = {name: paths[name] for name in wanted if name in paths}

    infos = {}
    for name, path in paths.items():
        try:
            infos[name] = sf.info(str(path))
        except Exception as error:
            raise StemValidationError(
                "stem {0} is not readable audio: {1}".format(path, error)
            ) from error

    rates = {name: info.samplerate for name, info in infos.items()}
    if len(set(rates.values())) != 1:
        raise StemValidationError(
            "supplied stems disagree on sample rate: {0}. The branches derive their "
            "frame hops from it, so they must all match.".format(rates)
        )
    channels = {name: info.channels for name, info in infos.items()}
    if len(set(channels.values())) != 1:
        raise StemValidationError(
            "supplied stems disagree on channel count: {0}".format(channels))
    frames = {name: info.frames for name, info in infos.items()}
    if len(set(frames.values())) != 1:
        raise StemValidationError(
            "supplied stems disagree on length in frames: {0}".format(frames))

    duration = next(iter(infos.values())).duration
    drift = abs(duration - float(source_duration_sec))
    if drift > DURATION_TOLERANCE_SEC:
        raise StemValidationError(
            "supplied stems are {0:.3f} s long but the source audio is {1:.3f} s "
            "({2:.3f} s apart, tolerance {3} s). These stems do not appear to belong to "
            "this audio.".format(duration, float(source_duration_sec), drift,
                                 DURATION_TOLERANCE_SEC)
        )

    return SeparationResult(
        stem_paths=paths,
        sample_rate=int(next(iter(rates.values()))),
        seconds=0.0,
        max_cuda_allocated=0,
        max_cuda_reserved=0,
        mode="supplied",
        stems_dir=stems_dir,
        model="",
    )
